name: Populate problems

on:
  push:
    branches:
      - main
    paths:
      - "apps/problems/**"

# defaults:
#   run:
#     working-directory: packages/db

jobs:
  setup_node:
    name: Setup Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: [setup_node]
    steps:
      - name: Install dependencies
        run: |
          ls
          npm ci

  populate_problems:
    name: Populate problems
    needs: [setup_node, install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
      - name: List all changed files and add them to DB
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run:
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [[ "$file" == apps/problems/* ]]; then
          folderName = $(awk -F/ '{print $2}' <<< "$file")
          echo "Populating for $folderName"
          npm run addProblem -- $folderName
          fi
          done
